[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
valorem_auction = "FG6nnyfyztJyn1Yzov6xHqfjRMJGTpHd6T5LwPJuruPS"
valorem_transfer_hook = "JCdjqNU5JEfuupjT6EAuBphhALhyiBRJy9E3fstwR1Yd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["valorem-auction", "valorem-transfer-hook"]
types = "../packages/valorem-sdk/src/idl/generated"

[scripts]
test = "npm run test:ts"
